doc. type. html
script
html
head
utf8
viewport content=width=device-width, initial-scale=one>
title covidstrings 3 championship bracket 
filename=covidstrings3 championship game .js
championship game=(high versus lowest remaining seed ) 
team high seed= highest remaining seed 
team low seed = lowest remaining seed
rounddiv=covid strings3  championship round
matchupclassname = matchup
matchupdiv.innerHTML =[team low seed versus team high seed]
rounddiv.appendchild(matchupdiv);
bracket.appendchild(rounddiv);
advancingteam =slice(currentteams) 
java util.scanner
java util
questions[]questions={
question28
question29
question30 
question31
question32
question33
question34 
collections.shuffle(arrays.aslist(questions)
class myclass
constructor (non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
const myclass=newmyclass(concatenated) 
return category
if category==math problem:
prompt
log
else:
select from multiple choice
import syntax 
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
declare winner
if team high seed score>sixty=:
console.log(team high seed wins covid strings3)
else:
console.log(team low seed wins covid strings3)
return filename
