doc.type.html
html lang en
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings3’
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=keywords
heading2=online references
heading3=script templates
filename=covid strings3 key words.js
let original string=”
let word to add-
let updated string {original string} {word to add}
console log updated string
<header.html>
keywords
key search words for covid strings3
covid strings 3 key word list=[pandemic time different than normal time,more,cough cured by soda and lemon juice,christmas isnt canceled just,not same fall of the masters,20*3,3.4*20,3.4*10-15,3.4*15-20,faucian,covid victory north korea,olympics odd year,unexplained special,price of oil ,covid strings games 30.73*24]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
string=””
for string in covid strings math problem list
select characters
edit diffuse property
desired color=green
<header.html>
online references 
links to articles that correspond to phrases in covid strings3 
covid strings3 reference list=[a:the coronavirus has warped all sense of time | wired, b: as who and cdc end covid-19 pandemic emergency,our readers share opinions :goats and soda :npr,c:monochronic vs polychronic:cultural differences explained(habitgrowth.com),d:https://www.reuters.com/article/uk-factcheck-coronavirus-alkaline/false-claim-baking-soda-and-lemon-juice-can-help-prevent-coronavirus-infection-iduskbm20x2bv,e:https://www.azlyrics.com/lyrics/kellyclarkson/christmasisntcanceledjustyou.html,f:https://www.augusta.com/masters/story/news/2020-11-07/fall-leaves-wont-be-only-change-2020-masters, 
g:world leaders preparing for disease 20 times deadlier than covid -us news,h:news -daily express us (the-express.com),i:what factors drove us gdp losses during the covid-19 pandemic? |j:world economic forum (weforum.org),the impact of the covid-19 pandemic on global gdp growth - k:pmc (nih.gov),what factors drove us gdp losses during the covid-19 pandemic?, |l:world economic forum (weforum.org),m:https://apnews.com/article/donald-trump-coronavirus-pandemic-health-0A36ebacea5bdaaf92204b9b79ebf0d6,n:north korea claims it eradicated covid and that kim jong un had fever -the washington post,o:https://sports.yahoo.com/olympics-tokyo-2020-in-2021-080605905.html,
p:https://www.imdb.com/title/tt14286524/,q:the price of oil fell below $ 0.what happens next? |pbs newshour, r:about covid-19 |smithsonian institution (si.edu).s:it will take years for the oil and gas market to recover from the mother of all shocks,harvard economist says (msn.com)
<header.html>
script templates
code for accessing the references
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize =function() 
console.log(this.foobar.name);
asset= this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
j=pc.create script(j);
j.attributes.add(foobar,{type:entity});
j.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.create script(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
l=pc.create script(l);
l.attributes.add(foobar,{type:entity});
l.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar= this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.createscript(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet(this.entity)
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instaniate
entity script foobar=this entity
entity reparnet(this.entity)
r=pc.create script(r);
r.attributes.add(foobar,{type:entity});
r.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
s=pc.create script(s);
s.attributes.add(foobar,{type:entity});
s.prototype.initialize =function() 
console.log(this.foobar.name);
return filename
